version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"
  secrets-manager:
    DOCKERHUB_USER: arn:aws:secretsmanager:ap-northeast-1:260130351964:secret:development/dockerhubSecret-LpZ664:username
    DOCKERHUB_PASS: arn:aws:secretsmanager:ap-northeast-1:260130351964:secret:development/dockerhubSecret-LpZ664:password
phases:
 install:
   runtime-versions:
     php: 7.4
 pre_build: # commands to be run before build
   commands:
   - echo bplms repository
   - echo Logging in to Amazon ECR....
   - aws --version
   # login to Elastic container registry
   - eval $(aws ecr get-login --region ap-northeast-1 --no-include-email | sed 's|https://||')
   # get login password for Docker Authentication
   #  - eval $(aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 533144182508.dkr.ecr.ap-northeast-1.amazonaws.com/bplms)
   # Docker Hub へのログイン
   - echo Logging in to Docker Hub...
   - echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
   - REPOSITORY_URI=260130351964.dkr.ecr.ap-northeast-1.amazonaws.com/wms
   - IMAGE_TAG=1.0
 build:
   commands:
   - echo Build started on `date`
   - echo Building the Docker image...
   - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
 post_build:
   commands:
     - echo Build completed on `date`
     - echo Pushing the Docker image...
     - docker image ls -a
     - docker push $REPOSITORY_URI:$IMAGE_TAG
     - echo Writing image definitions file...
     - echo "[{\"name\":\"docker-wms-container\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\"}]" > imagedefinitions.json
artifacts:
   files: imagedefinitions.json
